version: "1.1"
services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ".postgres-data:/var/lib/postgresql/data:delegated"
  web:
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+asyncpg://postgres:postgres@5432:localhost/postgres
    volumes:
      - .:/listing_app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db